### ISSUE TITLE
Best approach

### ISSUE THREAD

**Issue by Firedrake969** [ScratchAgarioBots/agario-bot#1]
Options:
* read through and create documentation, plan, then develop
* create a "battle plan", and create documentation as we develop

**Comment by PullJosh** [comment]
Option 2.

**Comment by Firedrake969** [comment]
Ok.  How do we test with it?

**Comment by Thepuzzlegame** [comment]
Option 1 is probably smarter, but I just wanna dive in so I'd prefer option 2.

**Comment by Firedrake969** [comment]
@Thepuzzlegame 
Option 2 will still work with TDD - we say we want it to accomplish something and then write code until it works.

**Comment by PullJosh** [comment]
We also need a versioning method. Let's not repeat MSU.

**Comment by Thepuzzlegame** [comment]
Here's a video on how to setup the bot: https://www.youtube.com/watch?v=fEVX4xmEn4s&feature=youtu.be

**Comment by PullJosh** [comment]
TDD?

**Comment by Thepuzzlegame** [comment]
Test-driven development

**Comment by PullJosh** [comment]
ah

**Comment by Firedrake969** [comment]
I know how to use the git console now :D

**Comment by Thepuzzlegame** [comment]
I can use the git console to some degree.

**Comment by PullJosh** [comment]
Github for windows ftw

**Comment by Firedrake969** [comment]
basically:
git status
git add -A
git commit -am "message here"
git pull origin branch-here
(fix conflicts)
git push origin branch-here

**Comment by Zaerospi** [comment]
I'm late.
So we are going to document as we go?

**Comment by Firedrake969** [comment]
Yeah, I think so

**Comment by Firedrake969** [comment]
How do we test it though?

**Comment by Thepuzzlegame** [comment]
https://www.youtube.com/watch?v=fEVX4xmEn4s&feature=youtu.be

**Comment by PullJosh** [comment]
If we make a git clone, and load extension in dev mode (as shown in video linked above), shouldn't clicking the "reload" button in chrome://extensions be sufficient?

**Comment by Zaerospi** [comment]
lol i see kerbal space program in his taskbar.

**Comment by Firedrake969** [comment]
Yeah, should be, PullJosh.

**Comment by Zaerospi** [comment]
PullJosh makes sense to me, but I've never worked with extension before.

**Comment by PullJosh** [comment]
Final decision is option 2: "Create a "battle plan", and create documentation as we develop".

If there are any objects, reopen this issue and give us your rant.
For other things, either open a new issue or use the scratch forum topic.
