### ISSUE TITLE
Allow User to Choose Name

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/agario-bot#10]

**Comment by PullJosh** [comment]
Added quick and dirty solution: 1b54b7afbe091d4aa4bc50270e49e5a0eac5d62e

Would love it if someone made a nicer looking one!

**Comment by matthewr6** [comment]
ew :P

**Comment by PullJosh** [comment]
I know...

**Comment by matthewr6** [comment]
Mind committing to complete-rewrite instead?

**Comment by PullJosh** [comment]
Is that the main thingamabob?

**Comment by PullJosh** [comment]
I'll commit there once I have a nicer looking one.

**Comment by matthewr6** [comment]
it's what I'm working on at least

**Comment by PullJosh** [comment]
Okay.

**Comment by an-OK-squirrel** [comment]
Darn, you caused a merge conflict now D:

**Comment by matthewr6** [comment]
wow
http://prntscr.com/7m5e6b
not bad!

**Comment by PullJosh** [comment]
Srry... I was gone all day, so I didn't know. :(

**Comment by matthewr6** [comment]
an-OK, do you use the command line or the gui?

**Comment by an-OK-squirrel** [comment]
command line. Also, do we need this? You could alway esc then choose it.

**Comment by PullJosh** [comment]
Gui, but sometimes github for windows, which does the exact same thing as the cmd line (essentially runs commands for you), only it's super user-friendly for git n00bs like me.

**Comment by PullJosh** [comment]
Wait... You can choose your name with esc? That's awesome! And no, then this isn't necessary.

**Comment by matthewr6** [comment]
command line is way more powerful :P

**Comment by PullJosh** [comment]
But way harder. :/

**Comment by matthewr6** [comment]
git status
git add -A
git commit -am "message here"
git pull origin branch
git push origin branch

**Comment by PullJosh** [comment]
click the sync button

**Comment by Firedrake969** [comment]
but you also have so many more powerful things in git commands

**Comment by PullJosh** [comment]
But I have an army of actually intelligent people who do all the hard command line stuff for me.

**Comment by matthewr6** [comment]
cmon PullJosh, you make really cool Scratch things
and you say you can only click "Sync", but not type 5 lines?

**Comment by an-OK-squirrel** [comment]
I don't even know what's happening...

**Comment by matthewr6** [comment]
lol
anyways
I should continue working on what I had planned

**Comment by PullJosh** [comment]
Science, my friend. Science is happening.
![image](https://cloud.githubusercontent.com/assets/5458180/8394456/e7ca6006-1d06-11e5-9b03-83fe9a621135.png)

(Except I'm not actually going to try cmd line)

**Comment by an-OK-squirrel** [comment]
![halp](https://cloud.githubusercontent.com/assets/12722625/8394457/8c45b4f4-1cfe-11e5-8f05-cea3bf7d020c.png)

**Comment by matthewr6** [comment]
What editor/theme is that?

**Comment by an-OK-squirrel** [comment]
notepad++

**Comment by matthewr6** [comment]
What are you changing atm?

**Comment by an-OK-squirrel** [comment]
I have this huge problem and all you say is "hat edider is zat?"

**Comment by an-OK-squirrel** [comment]
I git pulled and got that.

**Comment by matthewr6** [comment]
From what branch?

**Comment by an-OK-squirrel** [comment]
complete-rewrite.

**Comment by matthewr6** [comment]
Are you sure?  Try again :L

**Comment by PullJosh** [comment]
What are all the branches for anyway?

**Comment by matthewr6** [comment]
complete-rewrite is my testing stuff, the master is stuff I don't want to touch quite yet in case I break everything

**Comment by matthewr6** [comment]
should probably merge soon though

**Comment by an-OK-squirrel** [comment]
I get: error: you need to resolve you conflict before you do that

**Comment by PullJosh** [comment]
And runaway? What is that?

**Comment by matthewr6** [comment]
Do a rebase or reset

**Comment by an-OK-squirrel** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by an-OK-squirrel** [comment]
i figured it out, now I have to do it

**Comment by an-OK-squirrel** [comment]
Should be done!

**Comment by an-OK-squirrel** [comment]
I fixed da conflicts and they popped up again. AHH

**Comment by matthewr6** [comment]
maybe you need a break?  :P  I have to go soon to eat.

**Comment by an-OK-squirrel** [comment]
I doubt it.

**Comment by matthewr6** [comment]
For some reason tampermonkey doesn't like to update my scripts

**Comment by an-OK-squirrel** [comment]
AHHH ALL THE PROBLEMS
