### ISSUE TITLE
more effective food filtering

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#11]
make it so that it ignores food too close to bigger blobs

**Comment by an-OK-squirrel** [comment]
At least I wasn't assigned this..

**Comment by matthewr6** [comment]
I think I know how to do it pretty efficiently

**Comment by an-OK-squirrel** [comment]
Good. I don't

**Comment by PullJosh** [comment]
I could do it, but it would lag so bad. xD

**Comment by an-OK-squirrel** [comment]
When are you doing this?

**Comment by matthewr6** [comment]
Today I hope

**Comment by an-OK-squirrel** [comment]
good
