### ISSUE TITLE
Time for a pull request?

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#12]
thoughts?  It survives pretty well right now and can run away and eat on its own.

**Comment by an-OK-squirrel** [comment]
To master? After i FIX ALL DE CONFLICTS

**Comment by matthewr6** [comment]
i have no conflicts
you're just too aggressive so conflicts keep popping up :3

Seriously though what are you trying to do

**Comment by an-OK-squirrel** [comment]
I did the same thing you were doing, except not as good :P

**Comment by an-OK-squirrel** [comment]
I would remove it but I can't D:

**Comment by matthewr6** [comment]
we're one-for-one now :P  You made good dodging, I made good...
um...
food eating?

**Comment by matthewr6** [comment]
btw, if you want to reset your commits:
http://git-scm.com/docs/git-rebase
http://git-scm.com/docs/git-reset
http://stackoverflow.com/questions/9301782/need-to-reset-git-branch-to-origin-version

**Comment by an-OK-squirrel** [comment]
I think i did it.

**Comment by matthewr6** [comment]
Ok

**Comment by an-OK-squirrel** [comment]
..but I mistyped my password.

**Comment by matthewr6** [comment]
_facepalm_

**Comment by an-OK-squirrel** [comment]
:facepunch:

**Comment by an-OK-squirrel** [comment]
OK got it.

**Comment by matthewr6** [comment]
Did you change anything, or was it all fixing conflicts?

:facepunch: 

WAIT WHY IS A FISTBUMP CALLED FACEPUNCH

**Comment by matthewr6** [comment]
Um, the bot won't load now...

**Comment by an-OK-squirrel** [comment]
Oh no...

**Comment by PullJosh** [comment]
Seems to be ready to close.

If not, just reopen.
