### ISSUE TITLE
Blobs coming from either direction

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#13]
causes the player to just keep moving in the direction it was, rather than getting out at a right angle

**Comment by an-OK-squirrel** [comment]
Why?

**Comment by matthewr6** [comment]
The vectors probably cancel out so it just keeps going

**Comment by an-OK-squirrel** [comment]
I'll work on it!

**Comment by an-OK-squirrel** [comment]
I still don't know how though :P

**Comment by PullJosh** [comment]
Perhaps check if there are two large vectors that, when added together, result in a small vector? THat way you know it's being trapped.

Or something.

**Comment by an-OK-squirrel** [comment]
Ooh, that makes sense.

**Comment by PullJosh** [comment]
After [lines 820 and 820](https://github.com/ScratchAgarioBots/agario-bot/blob/master/bot.user.js#L820-L821), check to see if the length of the vector is relatively small. (Less than, say, 35.) If so, pick a perpendicular vector to the one you're currently on. (Would it work to just swap the x and y?)

**Comment by an-OK-squirrel** [comment]
(I know. :P)

**Comment by an-OK-squirrel** [comment]
I'll do this after lunch.

**Comment by PullJosh** [comment]
Okay, cool!

**Comment by matthewr6** [comment]
Status?

**Comment by an-OK-squirrel** [comment]
Nothing yet.

**Comment by an-OK-squirrel** [comment]
I have an idea.
