### ISSUE TITLE
Firedrake969 exclusively does the merge conflicts

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#14]
I had to resort to making a new branch.  No diffs or anything.  Huh.  I tried reverting, doing a hard reset, copy/pasting, git diff....

**Comment by an-OK-squirrel** [comment]
YESYESYES I AGREE YES

**Comment by an-OK-squirrel** [comment]
Wait. Are you saying you want to do them or it's an issue that you're doing them?

**Comment by PullJosh** [comment]
I think he's saying he should be the only one to do them, so that conflicts don't arise. Much less confusion that way.

**Comment by an-OK-squirrel** [comment]
YESYESYESYESYESYESYES I lost a lot of sleep last night over that merge.

**Comment by matthewr6** [comment]
Ok thanks guys
