### ISSUE TITLE
Add results

### ISSUE THREAD

**Issue by an-OK-squirrel** [ScratchAgarioBots/agario-bot#17]
5 results, average

**Comment by PullJosh** [comment]
What do you mean?

**Comment by an-OK-squirrel** [comment]
Like, run the bot for five  rounds and recotd the average of score and average

**Comment by an-OK-squirrel** [comment]
*record

**Comment by PullJosh** [comment]
What would the results be added to?

**Comment by an-OK-squirrel** [comment]
Maybe the results branch!

**Comment by PullJosh** [comment]
Oh. :3

**Comment by PullJosh** [comment]
We should probably track the results of each branch separately.

**Comment by an-OK-squirrel** [comment]
How about I do master and everyone else gets the results of their own branch?

**Comment by PullJosh** [comment]
Why would you do master?

**Comment by an-OK-squirrel** [comment]
Because I want to, that's why.

**Comment by an-OK-squirrel** [comment]
I mean, I assigned myself to the job..

**Comment by PullJosh** [comment]
Oh... I was thinking this was on a different issue. xD

Ignore me while I go hide in the corner in shame.

**Comment by an-OK-squirrel** [comment]
Making the results..
