### ISSUE TITLE
Trapped in Corner

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/agario-bot#18]
When being chased, sometimes the AI gets stuck in the corner and won't move.

Which sucks.

**Comment by an-OK-squirrel** [comment]
I remember seeing this.

**Comment by PullJosh** [comment]
I can't imagine how this could be fixed either...

**Comment by an-OK-squirrel** [comment]
Make the AI get away from edges when it can.

**Comment by PullJosh** [comment]
Fixed with #38.
