### ISSUE TITLE
Using as less functions from the original as possible

### ISSUE THREAD

**Issue by an-OK-squirrel** [ScratchAgarioBots/agario-bot#2]
Like getFood and stuff. They all seem to be based on getMemoryCells so we could write our own.

**Comment by matthewr6** [comment]
They seem to work pretty well, so I'd rather just work on the actual AI stuff.

**Comment by an-OK-squirrel** [comment]
What about the food clustering function?

**Comment by matthewr6** [comment]
Also seems to work well (at least for me)

**Comment by an-OK-squirrel** [comment]
Yeah, but my main point was that it's really part of their AI and not a necessary function, so we should rewrite it

**Comment by matthewr6** [comment]
We can keep it until we need to rewrite it

**Comment by an-OK-squirrel** [comment]
OK

**Comment by an-OK-squirrel** [comment]
You mean like rewriting to work with degrees?

**Comment by matthewr6** [comment]
No, just to make it work with how we want it

**Comment by an-OK-squirrel** [comment]
Wait, why don't we use radians anyway? Degrees suck in JS.

**Comment by matthewr6** [comment]
I'm just putting in conversions since degrees are more readable to me but radians are JS's default
