### ISSUE TITLE
Make results-making thing

### ISSUE THREAD

**Issue by an-OK-squirrel** [ScratchAgarioBots/agario-bot#21]
In the format of the thing I have on results

**Comment by PullJosh** [comment]
Yes, please. I'm at a score of 1030 and counting. It's getting quite boring just watching this thing.

**Comment by PullJosh** [comment]
(On my branch)

**Comment by an-OK-squirrel** [comment]
OOOOH!

**Comment by PullJosh** [comment]
Got a video too. :D

**Comment by PullJosh** [comment]
Can you just set the average for my bot to 1000 or something? I'm bored. :P

**Comment by an-OK-squirrel** [comment]
:P

**Comment by an-OK-squirrel** [comment]
Can you upload the video to YT?

**Comment by matthewr6** [comment]
Man, what server are you on?
My bot (even from your code) never gets that high.

**Comment by PullJosh** [comment]
I have no idea why it got that high. :P

**Comment by an-OK-squirrel** [comment]
Same.
