### ISSUE TITLE
Smaller Players Counted as One "Food"

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/agario-bot#25]
Snatching an enemy smaller than the AI is counted as being equivalent with eating one bit of food, meaning that smaller players are almost never chased by the AI.

**Comment by matthewr6** [comment]
I'll filter it

**Comment by matthewr6** [comment]
Probably ate tmrrow

**Comment by matthewr6** [comment]
Late

I'm on a phone

**Comment by PullJosh** [comment]
Can you merge the one pull request?

**Comment by PullJosh** [comment]
Once you're on a computer, of course.

**Comment by an-OK-squirrel** [comment]
See #23

**Comment by PullJosh** [comment]
Mostly fixed in `bufferless`. Continued improvements and tweaks there should do the trick. ;)
