### ISSUE TITLE
Need to stay further away from people 2x larger

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/agario-bot#29]
Even more extreme measures need to be taken to increase the buffer between the AI and other players who are twice as large (and, therefore, can shoot out at you). The current added distance is not enough.

**Comment by an-OK-squirrel** [comment]
Make it bigger then!

**Comment by PullJosh** [comment]
Done: #35

**Comment by matthewr6** [comment]
Should scale based on enemy size.

**Comment by matthewr6** [comment]
Also, buffers need to be reworked a LOT:
http://prntscr.com/7myj58

**Comment by PullJosh** [comment]
Yeah, I just stuck with how the buffers were earlier. I'll see if I can work on buffers at some point.

**Comment by PullJosh** [comment]
Fixed in `bufferless`.
