### ISSUE TITLE
Logo for organization

### ISSUE THREAD

**Issue by an-OK-squirrel** [ScratchAgarioBots/agario-bot#36]
Sorry, there isn't organization issues :/

**Comment by PullJosh** [comment]
Hmm...

**Comment by an-OK-squirrel** [comment]
I was thinking like a custom skin-looking thing with the ScratchCat face.

**Comment by PullJosh** [comment]
I'll work on it.

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8416009/b69283ea-1e70-11e5-963a-2119bc99b70f.png)

What do you think?

**Comment by an-OK-squirrel** [comment]
Nice!

**Comment by PullJosh** [comment]
It doesn't scale well, though. We need something that works as a favicon (as small as 16 x 16px)

**Comment by an-OK-squirrel** [comment]
Yeah.

**Comment by an-OK-squirrel** [comment]
Or as an org logo.

**Comment by PullJosh** [comment]
@Firedrake969 has been assigned, because he as the admin privileges.

**Comment by an-OK-squirrel** [comment]
OK
