### ISSUE TITLE
Brokenthing is broken

### ISSUE THREAD

**Issue by an-OK-squirrel** [ScratchAgarioBots/agario-bot#37]
Why?

**Comment by PullJosh** [comment]
It's all in the name, my friend. All in the name.

...

I have no idea.

**Comment by an-OK-squirrel** [comment]
I'm out of here for today, so I'll do stuffz tommorow..

**Comment by matthewr6** [comment]
What's borked?

**Comment by an-OK-squirrel** [comment]
Just doesn't work

**Comment by Znapi** [comment]
I don't know how to fix it, but when you are inside `(function(f, g) {...})(window, jquery)`, why not reference `window` with `f` instead?

**Comment by Znapi** [comment]
It's because whenever you try to add a third level(idk if there is a better term) in `window`, it messes up for some reason. Here:

```
window.mystuff = 42;

(function(f, g) {
    console.log(f.mystuff);
    ...
```

That works. But for some reason this:

```
window.mystuff.anotherlevel = 42;

(function(f, g) {
    console.log(f.mystuff.anotherlevel);
    ...
```

causes the bot to not work at all.

**Comment by matthewr6** [comment]
Try to keep stuff in the function so we have everything in scope.
Also, window.mystuff hasn't been declared in your second example, so it'll break in any sort of JS interpreter.

**Comment by Znapi** [comment]
~~That must be why it is breaking an-OK-squirrels's branch!~~
Oh wait, I see what I did wrong...

**Comment by matthewr6** [comment]
Yeah - you have to declare an object property's parent before you declare the property :P

**Comment by Znapi** [comment]
Aha! Found it for real this time. You are missing an equal sign in `function foodValue` on line 718:

```
                var dangerous computeDistance(food[0], food[1], enemy.x, enemy.y) <= player.size + enemy.size + buffer;
```

**Comment by an-OK-squirrel** [comment]
thanks!

**Comment by PullJosh** [comment]
From what I can see, this appears to be fixed. Someone who actually knows things, please close this if it is.

**Comment by an-OK-squirrel** [comment]
It's outdated amyway
