### ISSUE TITLE
Labels we need

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/agario-bot#4]
Github allows custom issue labels. I've created an "additional factor" label. This is for issues that contain ideas for new things the bot should consider. What other labels would be helpful for this project? Are there any defaults that aren't needed?

**Comment by Firedrake969** [comment]
NO JOKE LABELS, PLEASE.

That aside, we'd also want a "building feature" label or something to discuss features we're building into the bot.

**Comment by PullJosh** [comment]
How about "in progress"?

**Comment by Firedrake969** [comment]
That's the whole project, though :P

**Comment by PullJosh** [comment]
But, like, specific things that are currently being coded by someone. This would prevent duplicates of the same feature.

**Comment by PullJosh** [comment]
After all, isn't that what you meant when you said "building feature"? I was just paraphrasing.

**Comment by Firedrake969** [comment]
We could keep track on a separate issue continuously maintained.

**Comment by PullJosh** [comment]
Wouldn't it make more sense to use a label though? That way you can see, directly on an issue, whether it's already being worked on.

**Comment by Firedrake969** [comment]
Maybe both?

**Comment by PullJosh** [comment]
That seems a bit overcomplicated. Let's get someone else's opinion.

(I'm looking at you @Thepuzzlegame @Zaerospi)

**Comment by Zaerospi** [comment]
uhhh...I really don't know. Just the word "maintaining" sounds like word though. Maybe a wiki page, or a TODO file in the repo that says who is doing what? Because then everyone can edit it, and it won't flood the issues.

**Comment by Zaerospi** [comment]
*work, not word

**Comment by Firedrake969** [comment]
Everyone can edit an issue post too :P

**Comment by Zaerospi** [comment]
Oh. I'm a n00b obviously.

**Comment by PullJosh** [comment]
What would be the benefit of having the labels and a dedicated issue? You can view all the issues with a certain label anyway.

**Comment by Firedrake969** [comment]
True, forgot about that.  Let's just have individual labels.

**Comment by PullJosh** [comment]
How about a "planning" label, for issues like this one?

**Comment by Zaerospi** [comment]
Individual labels would allow discussion about that specific feature in one thread, so individual.

**Comment by PullJosh** [comment]
What do you mean by "individual labels"?

**Comment by Zaerospi** [comment]
planning label sounds nice.

**Comment by PullJosh** [comment]
But is it helpful? Just because it rolls off the tongue doesn't mean it's necessary.

**Comment by Zaerospi** [comment]
Sorry, I meant individual issues. I mean planning sounds like a good word to label these "issues" with.

**Comment by PullJosh** [comment]
Ah, I see what you mean. Okay...

**Comment by PullJosh** [comment]
Seems pretty well taken care of. Closing to get this out of the way. If anyone still wants to add to this, feel free to re-open.
