### ISSUE TITLE
Default to hide names?

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#40]
If we plan to show this on Scratch, we should probably have it default to hiding names.

**Comment by heyseth** [comment]
Done. Gonna add some extra code tomorrow that will remember if the user unchecks "No names" and will no longer set names to hidden by default. Right now though I'm too tired and it's too late.

**Comment by Thepuzzlegame** [comment]
Additionally I was thinking maybe we should also have skins disabled by default as some of them are potentially offensive.

**Comment by PullJosh** [comment]
Yay! I hate names.

(I mean, agar.io ones. Real life names are cool.)

**Comment by PullJosh** [comment]
Closing due to finishedness.
