### ISSUE TITLE
Rank running away from bots

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#42]
in order of closest to farthest

**Comment by PullJosh** [comment]
We should also make the bot realise that bots that are _way_ bigger than it won't really go after it at at all. If you're size 100, and you're between a size 2000 who's 50px away, and a size 150 who's 100px away, you should still run from the 150.

**Comment by an-OK-squirrel** [comment]
Yes, but what whould it actually do?

**Comment by an-OK-squirrel** [comment]
The sort is really easy, I'll do it today.

**Comment by PullJosh** [comment]
I'm just saying that if you're, say, less than 10% of the size of another bot, you don't really have to worry too much about them going after you. Don't commit suicide, of course, but staying far enough away that the can't press space to nab you is kind of overkill.

**Comment by matthewr6** [comment]
yeah

**Comment by matthewr6** [comment]
And buffers really should scale

**Comment by an-OK-squirrel** [comment]
Yeah

**Comment by an-OK-squirrel** [comment]
Wait, but smaller cells go faster...

**Comment by PullJosh** [comment]
Added as a part of `bufferless`.
