### ISSUE TITLE
Tile-based and pathfinding?

### ISSUE THREAD

**Issue by Znapi** [ScratchAgarioBots/agario-bot#50]
What if we separated the level into a bunch of hexagonal tiles that are about the same size as the bot? Hexagons because they are rounder than squares, but still fit together. Then, each tile could have a value, called the weight, that reflects how much mass can be gained from that tile minus how risky it is. This would allow the bot to be able to weigh risks and make decisions. The gradient buffers were a great step towards that. It could even look ahead and make paths to follow by choosing a destination cell, and choosing cells inbetween to travel through that have relatively high weight.

This would be a relatively big change, but it would go on top of what you guys have already. Food, clusters, and super clusters are still cycled through, and enemies too. Enemies will still use gradients in affecting the weights of the tiles around them.

Idk, just making ideas. Plus I was having fun and made a hexagon tile overlay while going through the source code and refreshing my JS. https://github.com/ScratchAgarioBots/agario-bot/tree/tiles Maybe it is too much of a change?
Also, I know I haven't been active, but I am ready to be now.

**Comment by matthewr6** [comment]
I think it's too different from the path we've been pursuing, and to me it doesn't fit our goal, which is to stay alive.  If a tile has lots of food but it's high risk, we'd rather to to a tile with low food and low risk, but those would probably have similar scores.
Probably worded that badly.
