### ISSUE TITLE
Who uses the command line?

### ISSUE THREAD

**Issue by Firedrake969** [ScratchAgarioBots/agario-bot#6]
just curious.

**Comment by PullJosh** [comment]
l33t hax0rs.

Not me.

**Comment by Firedrake969** [comment]
I have to go for now, bye.
Due to real life things I can't really code from 9 - 4 MST Mon-Thurs and 9 - 1 Friday, but I can  discuss

**Comment by Thepuzzlegame** [comment]
I do

**Comment by Firedrake969** [comment]
Nice.  What OS and shell?  I use iTerm2 (OS X) and Cmder with cmd (Win8.1)

**Comment by Thepuzzlegame** [comment]
Windows 8.1 and Console2 with cmd.

**Comment by Thepuzzlegame** [comment]
Cmder looks pretty nice though, maybe I'll switch...

**Comment by Firedrake969** [comment]
I don't like Windows' native cmd.  Is Console/Console2 just built on top of that, or does it have functions like ls and pwd?

**Comment by Thepuzzlegame** [comment]
Console2 is just a front-end for existing shells. It adds things like multiple tabs for different shells, text selection, background transparency, additional fonts, etc.

**Comment by Firedrake969** [comment]
Ok, I think I prefer Cmder, since it can emulate bash commands and stuff :P

**Comment by Thepuzzlegame** [comment]
I guess I'm just used to batch. If I want to use bash commands I use win-bash.

**Comment by Firedrake969** [comment]
Ever used iTerm2?  It's amazing.

**Comment by Thepuzzlegame** [comment]
I don't have a mac :P

**Comment by Firedrake969** [comment]
I use cmder so I can use bash and normal command line at the same time

anyways I'll close this now
