### ISSUE TITLE
Bot occasionally goes towards others instead of away

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#7]

**Comment by an-OK-squirrel** [comment]
It does nothing for me. I just made my own AI locally, pushing to new branch now...

**Comment by matthewr6** [comment]
I'm using Chrome with Tampermonkey.  You?

**Comment by an-OK-squirrel** [comment]
Greasemonkey, Firefox. To me it looked like the code.

**Comment by matthewr6** [comment]
Nothing's wrong with the code.  I've put it through JSHint, and the console isn't showing any errors.

**Comment by matthewr6** [comment]
Sorry, my bad.  Forgot to push xD

**Comment by an-OK-squirrel** [comment]
I mean the code doesn't tell the bot to move. :P Anyway, check out the runaway branch.

**Comment by matthewr6** [comment]
Wait check mine out again - I forgot to push up everything

**Comment by an-OK-squirrel** [comment]
KK

**Comment by an-OK-squirrel** [comment]
mine works better

**Comment by matthewr6** [comment]
Ok, I'll merge it into mine and copy your style

**Comment by an-OK-squirrel** [comment]
ahh merge conflicts
