### ISSUE TITLE
Add "get super clusters" function

### ISSUE THREAD

**Issue by matthewr6** [ScratchAgarioBots/agario-bot#9]
find clusters of clusters (ie 5+ or 10+ food items relatively close together - say, 150 radius)

**Comment by an-OK-squirrel** [comment]
Do we need this?

**Comment by matthewr6** [comment]
Yeah.  It filters from get super clusters to get clusters to get individual food items

**Comment by PullJosh** [comment]
Agreed.

**Comment by matthewr6** [comment]
I had something but it got removed by accident

**Comment by PullJosh** [comment]
Nice.

**Comment by an-OK-squirrel** [comment]
Couldn't you use the cluster function on itself?

**Comment by matthewr6** [comment]
No, because of the way the cluster function is written.

**Comment by an-OK-squirrel** [comment]
Then rewrite it, silly!

**Comment by matthewr6** [comment]
I finished this already

**Comment by an-OK-squirrel** [comment]
Oh. :P
